### ISSUE TITLE
atom-maven expects $PATH to contain the string 'maven' or 'M2' or 'M3'

### ISSUE THREAD

**Issue by giorgian** [concon121/atom-maven#43]
I've just installed atom-maven and all new atom windows show:

> Maven has not been found on the $PATH, please ensure that Maven has been installed.

This happens in `MavenUtils#getMavenGlobalSettings`, that checks PATH elements for `/^.*(maven)|(M2)|(M3).*$/g`.

I installed Maven via homebrew and didn't need to edit my PATH environment variable.

I _could_ add `/usr/local/Cellar/maven/VERSION/libexec/bin/` to my PATH, but then I'd have to remember to change it whenever Maven gets updated, and that seems unnecessarily annoying.

I don't know if there's a better way to programmatically determine the location of the global settings.xml than:

```
mvn -X | grep 'global settings'
```

But I'd rather accept to change some configuration somewhere in Atom than to mess with the PATH environment variable every time I upgrade Maven.

**Comment by concon121** [comment]
Adding in a configuration element for your maven installation which if set will take presenence over automatic discovery.

Will be available in the upcoming release.

Thanks for raising this issue!
