### ISSUE TITLE
Configurable .classpath file name

### ISSUE THREAD

**Issue by endymuhardin** [concon121/atom-maven#70]
Both linter-javac and autocomplete-java have configurable .classpath file name to avoid conflict with Eclipse. 
It would be nice if atom-maven also has corresponding configurable file name so that we can avoid .classpath file name altogether.

**Comment by concon121** [comment]
Hi @endymuhardin , thanks for your feature request!  I've put this in for you and released a new version 1.1.0.  Let me know how if it works for you!

**Comment by concon121** [comment]
No response from OP, closing this issue as completed.
