### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by belgoros** [concon121/atom-maven#91]
I got this error when installing the package.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.3.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/Serguei/projects/learn-java/effective.pom'

```
At fs.js:640

Error: ENOENT: no such file or directory, open '/Users/Serguei/projects/learn-java/effective.pom'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:49:29
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:71:7
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
     -2:11.9.0 settings-view:open (div.tool-panel.tree-view)
  2x -2:02.5.0 core:confirm (input.hidden-input)
     -0:51.7.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:49.7.0 core:confirm (input.hidden-input)
     -0:27.4.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:25.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-maven 1.3.0 
railscast-theme 0.3.0 
cucumber 0.6.0 
cucumber-autocomplete 0.7.2 
rails-rspec 0.3.2 
rspec 0.3.2 
```

**Comment by concon121** [comment]
Just a couple of questions to help me debug this issue:

1. Does the effective.pom file exist in the referenced directory?
2. Was the effective.pom file deleted by yourself or any third party apps?
3. Do you as the user that opened atom, have permissions to write to the referenced directory?

Any other info you can provide would be extremely helpful. Thanks!

**Comment by belgoros** [comment]
@concon121 I can't reproduce the issue any more. I uninstalled the plugin. I think it was a corporate proxy settings problem. After re-installing it without proxy, everything seems to work as needed.
Regards
